
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Image;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.io.File;
import javax.swing.ComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;



/**
 *
 * @author Zoher
 */
public class FormPanel extends javax.swing.JPanel {
    /**
     * Creates new form FormPanel
     */
    JPanel bottompanel;
    private String imagePath;
    public FormPanel(JPanel bottompanel) {
        initComponents();
        this.bottompanel = bottompanel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gendergroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        fnamelabel = new javax.swing.JLabel();
        lnamelabel = new javax.swing.JLabel();
        agelabel = new javax.swing.JLabel();
        emaillabel = new javax.swing.JLabel();
        symptomlabel = new javax.swing.JLabel();
        fnametextfield = new javax.swing.JTextField();
        ltextfield = new javax.swing.JTextField();
        agetextfield = new javax.swing.JTextField();
        emailtextfield = new javax.swing.JTextField();
        genderlabel = new javax.swing.JLabel();
        patientcombo = new javax.swing.JComboBox<>();
        patientlabel = new javax.swing.JLabel();
        documentslabel = new javax.swing.JLabel();
        uploadbutton = new javax.swing.JButton();
        submitbutton = new javax.swing.JButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        messagefield = new javax.swing.JTextField();
        jRadioButton4 = new javax.swing.JRadioButton();
        jMonthChooser1 = new com.toedter.calendar.JMonthChooser();
        jLabel2 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(700, 525));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Form");
        jLabel1.setMaximumSize(new java.awt.Dimension(30, 15));

        fnamelabel.setText("First name");

        lnamelabel.setText("Last name");

        agelabel.setText("Age");

        emaillabel.setText("Email");

        symptomlabel.setText("Symptom");

        fnametextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnametextfieldActionPerformed(evt);
            }
        });

        ltextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ltextfieldActionPerformed(evt);
            }
        });

        agetextfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                agetextfieldKeyPressed(evt);
            }
        });

        emailtextfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                emailtextfieldKeyPressed(evt);
            }
        });

        genderlabel.setText("Gender");

        patientcombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ","Emergency", "Regular", "Dentist", "ECG"}));
        patientcombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientcomboActionPerformed(evt);
            }
        });

        patientlabel.setText("Patient type");

        documentslabel.setText("Documents");

        uploadbutton.setText("Upload");
        uploadbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadbuttonActionPerformed(evt);
            }
        });

        submitbutton.setText("Submit");
        submitbutton.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/submit.png"))); // NOI18N
        submitbutton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/submit.png"))); // NOI18N
        submitbutton.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/submit.png"))); // NOI18N
        submitbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitbuttonActionPerformed(evt);
            }
        });

        gendergroup.add(jRadioButton2);
        jRadioButton2.setText("Female");
        jRadioButton2.setActionCommand("FEMALE");

        gendergroup.add(jRadioButton3);
        jRadioButton3.setText("Other");
        jRadioButton3.setActionCommand("OTHER");

        gendergroup.add(jRadioButton4);
        jRadioButton4.setText("Male");
        jRadioButton4.setActionCommand("MALE");

        jLabel2.setText("Month");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fnamelabel)
                                    .addComponent(lnamelabel)
                                    .addComponent(agelabel)
                                    .addComponent(symptomlabel)
                                    .addComponent(emaillabel)
                                    .addComponent(genderlabel))
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jRadioButton4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jRadioButton2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jRadioButton3))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(emailtextfield, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(agetextfield, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(ltextfield, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(fnametextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(messagefield, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(patientlabel)
                                    .addComponent(documentslabel)
                                    .addComponent(jLabel2))
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(uploadbutton)
                                    .addComponent(jMonthChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(patientcombo, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(299, 299, 299)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addComponent(submitbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(235, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fnamelabel)
                    .addComponent(fnametextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lnamelabel)
                    .addComponent(ltextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agelabel)
                    .addComponent(agetextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emaillabel)
                    .addComponent(emailtextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(symptomlabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(messagefield, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(genderlabel)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jRadioButton4)
                        .addComponent(jRadioButton2)
                        .addComponent(jRadioButton3)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patientcombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(patientlabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(documentslabel)
                    .addComponent(uploadbutton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jMonthChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(submitbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2))
                .addGap(26, 26, 26))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void fnametextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnametextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnametextfieldActionPerformed

    private void ltextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ltextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ltextfieldActionPerformed

    private void patientcomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientcomboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_patientcomboActionPerformed

    private void uploadbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadbuttonActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        int result = fileChooser.showOpenDialog(this);

        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            imagePath = selectedFile.getAbsolutePath();
            
        }
    }//GEN-LAST:event_uploadbuttonActionPerformed

    private void submitbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitbuttonActionPerformed
        // TODO add your handling code here:
        User newuser = new User();
        
        ImageIcon icon = new ImageIcon(imagePath);
        Image image = icon.getImage().getScaledInstance(150, 150, Image.SCALE_DEFAULT);
        
        ImageIcon scaledIcon = new ImageIcon(image);
         
        newuser.setFirstname(fnametextfield.getText());
        newuser.setLastname(ltextfield.getText());
        newuser.setAge(agetextfield.getText());
        newuser.setEmail(emailtextfield.getText());
        newuser.setGender(gendergroup.getSelection().getActionCommand());
        newuser.setPatientType(patientcombo.getSelectedItem().toString());
        newuser.setMessage(messagefield.getText());
      
        ViewPanel viewObject = new ViewPanel(newuser,bottompanel,scaledIcon);
        bottompanel.add(viewObject);
        CardLayout layout = (CardLayout) this.bottompanel.getLayout();
        layout.next(bottompanel);
       

        
        
         
         
    }//GEN-LAST:event_submitbuttonActionPerformed

    private void agetextfieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_agetextfieldKeyPressed
        // TODO add your handling code here:
         try{
            
            int age = Integer.parseInt(agetextfield.getText());
            
            agetextfield.setForeground(Color.black);
            
        }
        catch(NumberFormatException e){
            
            agetextfield.setForeground(Color.red);

        }
    }//GEN-LAST:event_agetextfieldKeyPressed

    private void emailtextfieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emailtextfieldKeyPressed
        // TODO add your handling code here:
        
         try{
             
             if (emailtextfield.getText().matches("^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$")){
                 
                 emailtextfield.setForeground(Color.black);

            }
            
            else{
                throw new Exception();
            }
                        
        }
        catch(Exception e){
            
            emailtextfield.setForeground(Color.red);
    }//GEN-LAST:event_emailtextfieldKeyPressed

    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel agelabel;
    private javax.swing.JTextField agetextfield;
    private javax.swing.JLabel documentslabel;
    private javax.swing.JLabel emaillabel;
    private javax.swing.JTextField emailtextfield;
    private javax.swing.JLabel fnamelabel;
    private javax.swing.JTextField fnametextfield;
    private javax.swing.ButtonGroup gendergroup;
    private javax.swing.JLabel genderlabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private com.toedter.calendar.JMonthChooser jMonthChooser1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JLabel lnamelabel;
    private javax.swing.JTextField ltextfield;
    private javax.swing.JTextField messagefield;
    private javax.swing.JComboBox<String> patientcombo;
    private javax.swing.JLabel patientlabel;
    private javax.swing.JButton submitbutton;
    private javax.swing.JLabel symptomlabel;
    private javax.swing.JButton uploadbutton;
    // End of variables declaration//GEN-END:variables

}